<?php

namespace App\Services;

use App\Legacy\Paths;
use Illuminate\Database\Connection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;

class DatabaseBackup
{
    /** Streaming SQL avoids shell interpolation, credentials in argv, and large RAM dumps. */
    public function create(?Connection $connection = null, ?string $directory = null): array
    {
        $connection ??= DB::connection();
        $directory ??= Paths::backups();
        File::ensureDirectoryExists($directory, 0700);
        $name = 'absen_db_backup_'.date('Y-m-d_H-i-s').'_'.bin2hex(random_bytes(4)).'.sql';
        $temporary = $directory.'/'.$name.'.partial';
        $path = $directory.'/'.$name;
        $stream = fopen($temporary, 'xb');
        if (! $stream) {
            throw new \RuntimeException('Tidak dapat membuat file backup.');
        }
        try {
            $pdo = $connection->getPdo();
            $driver = $connection->getDriverName();
            if (! in_array($driver, ['mysql', 'sqlite'], true)) {
                throw new \RuntimeException('Driver backup tidak didukung.');
            }
            fwrite($stream, "-- Absen verified-format SQL backup\n");
            fwrite($stream, $driver === 'mysql' ? "SET FOREIGN_KEY_CHECKS=0;\n" : "PRAGMA foreign_keys=OFF;\n");
            $connection->beginTransaction();
            $tables = $driver === 'mysql'
                ? $pdo->query("SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'")->fetchAll(\PDO::FETCH_COLUMN)
                : $pdo->query("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")->fetchAll(\PDO::FETCH_COLUMN);
            foreach ($tables as $table) {
                $quoted = '`'.str_replace('`', '``', $table).'`';
                $ddl = $driver === 'mysql'
                    ? $pdo->query('SHOW CREATE TABLE '.$quoted)->fetch(\PDO::FETCH_NUM)[1]
                    : $pdo->query('SELECT sql FROM sqlite_master WHERE type=\'table\' AND name='.$pdo->quote($table))->fetchColumn();
                fwrite($stream, 'DROP TABLE IF EXISTS '.$quoted.";\n".$ddl.";\n");
                $columns = array_filter($connection->getSchemaBuilder()->getColumns($table), fn ($column) => empty($column['generation']));
                $names = array_map(fn ($column) => '`'.str_replace('`', '``', $column['name']).'`', $columns);
                $selection = implode(',', $names);
                $rows = $pdo->query('SELECT '.$selection.' FROM '.$quoted);
                while ($row = $rows->fetch(\PDO::FETCH_NUM)) {
                    $values = array_map(fn ($value) => $value === null ? 'NULL' : $pdo->quote((string) $value), $row);
                    fwrite($stream, 'INSERT INTO '.$quoted.' ('.$selection.') VALUES ('.implode(',', $values).");\n");
                }
                // SQLite indexes are separate from CREATE TABLE.
                if ($driver === 'sqlite') {
                    foreach ($pdo->query('SELECT sql FROM sqlite_master WHERE type=\'index\' AND sql IS NOT NULL AND tbl_name='.$pdo->quote($table))->fetchAll(\PDO::FETCH_COLUMN) as $index) {
                        fwrite($stream, $index.";\n");
                    }
                }
            }
            $connection->commit();
            fwrite($stream, $driver === 'mysql' ? "SET FOREIGN_KEY_CHECKS=1;\n" : "PRAGMA foreign_keys=ON;\n");
            if (! fflush($stream)) {
                throw new \RuntimeException('Backup flush gagal.');
            }
            fclose($stream);
            if (! rename($temporary, $path)) {
                throw new \RuntimeException('Publikasi backup gagal.');
            }
            $digest = hash_file('sha256', $path);
            file_put_contents($path.'.sha256', $digest);

            return ['ok' => true, 'success' => true, 'message' => 'Backup berhasil dibuat.', 'filename' => $name, 'path' => $path, 'size' => filesize($path), 'sha256' => $digest];
        } catch (\Throwable $e) {
            if ($connection->transactionLevel() > 0) {
                $connection->rollBack();
            }
            if (is_resource($stream)) {
                fclose($stream);
            }
            // Keep .partial for diagnosis; never publish or purge old backups on failure.
            throw $e;
        }
    }

    public function prune(string $directory): void
    {
        $files = glob($directory.'/absen_db_backup_*.sql') ?: [];
        usort($files, fn ($a, $b) => filemtime($b) <=> filemtime($a));
        foreach (array_slice($files, config('backup.keep')) as $path) {
            if (is_link($path)) {
                continue;
            }
            // Only files generated by this service (with checksum) are eligible.
            if (is_file($path.'.sha256')) {
                unlink($path);
                unlink($path.'.sha256');
            }
        }
    }
}
